import { Customer, Invoice, Payment, ShopUser } from '../types';

/**
 * Exports a clean, formatted CSV with UTF-8 BOM so Excel opens it flawlessly.
 */
export function downloadCustomerCsv(
  shop: ShopUser | null,
  customer: Customer,
  invoices: Invoice[],
  payments: Payment[]
) {
  const shopName = shop?.shop_name || 'Udhari Business';
  const totalCredit = invoices.reduce((sum, inv) => sum + (inv.total_amount || 0), 0);
  const totalPaid = payments.reduce((sum, pay) => sum + (pay.amount || 0), 0);
  const balanceDue = customer.current_balance || Math.max(0, totalCredit - totalPaid);

  // Combine and sort chronologically (oldest to newest)
  type Entry = {
    date: string;
    type: 'BILL' | 'PAYMENT';
    ref: string;
    desc: string;
    debit: number;
    credit: number;
  };

  const entries: Entry[] = [];

  invoices.forEach((inv) => {
    const items = (inv.items || [])
      .map((i) => `${i.item_name} (Qty: ${i.quantity}, Rate: Rs.${i.unit_price})`)
      .join('; ');
    entries.push({
      date: inv.created_at,
      type: 'BILL',
      ref: inv.invoice_number || 'INV',
      desc: items || inv.notes || 'Credit Bill',
      debit: inv.total_amount || 0,
      credit: 0,
    });
  });

  payments.forEach((pay) => {
    const note = pay.reference_note ? `${pay.payment_mode} - ${pay.reference_note}` : pay.payment_mode;
    entries.push({
      date: pay.created_at,
      type: 'PAYMENT',
      ref: pay.receipt_number || 'PAY',
      desc: `Payment Received (${note})`,
      debit: 0,
      credit: pay.amount || 0,
    });
  });

  entries.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  // Build CSV content with UTF-8 BOM
  let csv = '\uFEFF'; // Excel UTF-8 BOM

  // --- BUSINESS HEADER ---
  csv += `========================================================\n`;
  csv += `CUSTOMER ACCOUNT LEDGER STATEMENT\n`;
  csv += `========================================================\n\n`;

  csv += `BUSINESS DETAILS\n`;
  csv += `Shop Name,"${shopName.replace(/"/g, '""')}"\n`;
  if (shop?.owner_name) csv += `Owner Name,"${shop.owner_name.replace(/"/g, '""')}"\n`;
  if (shop?.phone) csv += `Contact Phone,"${shop.phone}"\n`;
  if (shop?.address) csv += `Address,"${shop.address.replace(/"/g, '""')}"\n`;
  if (shop?.gstin) csv += `GSTIN,"${shop.gstin}"\n`;
  csv += `\n`;

  // --- CUSTOMER SUMMARY ---
  csv += `CUSTOMER DETAILS\n`;
  csv += `Customer Name,"${customer.name.replace(/"/g, '""')}"\n`;
  csv += `Mobile Number,"${customer.phone}"\n`;
  if (customer.address_landmark) csv += `Address / Landmark,"${customer.address_landmark.replace(/"/g, '""')}"\n`;
  csv += `Statement Date,"${new Date().toLocaleDateString('en-IN')} ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}"\n`;
  csv += `\n`;

  // --- FINANCIAL SUMMARY CARDS ---
  csv += `FINANCIAL SUMMARY\n`;
  csv += `Total Credit Taken (Rs.),${totalCredit}\n`;
  csv += `Total Amount Paid (Rs.),${totalPaid}\n`;
  csv += `Net Balance Due (Rs.),${balanceDue}\n`;
  csv += `\n`;

  // --- ITEMIZED TRANSACTION TABLE ---
  csv += `========================================================\n`;
  csv += `TRANSACTION BREAKDOWN (Chronological)\n`;
  csv += `========================================================\n`;
  csv += `Date,Time,Type,Reference #,Particulars / Item Details,Debit (+) Rs.,Credit (-) Rs.,Running Balance Rs.\n`;

  let runningBalance = 0;
  entries.forEach((e) => {
    const dt = new Date(e.date);
    const dateStr = dt.toLocaleDateString('en-IN');
    const timeStr = dt.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

    if (e.type === 'BILL') {
      runningBalance += e.debit;
    } else {
      runningBalance = Math.max(0, runningBalance - e.credit);
    }

    csv += `"${dateStr}","${timeStr}","${e.type === 'BILL' ? 'Credit Purchase' : 'Payment Paid'}","${e.ref}","${e.desc.replace(/"/g, '""')}",${e.debit},${e.credit},${runningBalance}\n`;
  });

  csv += `\n`;
  csv += `*** End of Statement - Generated by Udhari Smart Ledger ***\n`;

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute(
    'download',
    `${customer.name.replace(/\s+/g, '_')}_Statement_${new Date().toISOString().slice(0, 10)}.csv`
  );
  document.body.appendChild(link);
  link.click();
  link.remove();
}

/**
 * Opens a print-ready, professional A4 Customer Statement window with print & PDF download.
 */
export function printCustomerStatement(
  shop: ShopUser | null,
  customer: Customer,
  invoices: Invoice[],
  payments: Payment[]
) {
  const shopName = shop?.shop_name || 'Udhari Business';
  const totalCredit = invoices.reduce((sum, inv) => sum + (inv.total_amount || 0), 0);
  const totalPaid = payments.reduce((sum, pay) => sum + (pay.amount || 0), 0);
  const balanceDue = customer.current_balance || Math.max(0, totalCredit - totalPaid);

  type Entry = {
    date: string;
    type: 'BILL' | 'PAYMENT';
    ref: string;
    desc: string;
    debit: number;
    credit: number;
  };

  const entries: Entry[] = [];

  invoices.forEach((inv) => {
    const items = (inv.items || [])
      .map((i) => `<strong>${i.item_name}</strong> (Qty: ${i.quantity} &times; ₹${i.unit_price} = ₹${i.subtotal})`)
      .join('<br/>');
    entries.push({
      date: inv.created_at,
      type: 'BILL',
      ref: inv.invoice_number || 'INV',
      desc: items || inv.notes || 'Credit Bill',
      debit: inv.total_amount || 0,
      credit: 0,
    });
  });

  payments.forEach((pay) => {
    const note = pay.reference_note ? `${pay.payment_mode} - ${pay.reference_note}` : pay.payment_mode;
    entries.push({
      date: pay.created_at,
      type: 'PAYMENT',
      ref: pay.receipt_number || 'PAY',
      desc: `Payment Received (${note})`,
      debit: 0,
      credit: pay.amount || 0,
    });
  });

  entries.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  let runningBalance = 0;
  const rowsHtml = entries
    .map((e) => {
      const dt = new Date(e.date);
      const dateStr = dt.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
      const timeStr = dt.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

      if (e.type === 'BILL') {
        runningBalance += e.debit;
      } else {
        runningBalance = Math.max(0, runningBalance - e.credit);
      }

      const isBill = e.type === 'BILL';
      return `
      <tr>
        <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px;">
          ${dateStr}<br/><span style="color: #6b7280; font-size: 11px;">${timeStr}</span>
        </td>
        <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 12px;">
          <span style="display: inline-block; padding: 2px 8px; border-radius: 4px; font-weight: 600; font-size: 11px; background: ${isBill ? '#fef2f2' : '#f0fdf4'}; color: ${isBill ? '#b91c1c' : '#15803d'};">
            ${isBill ? 'Bill' : 'Payment'}
          </span>
          <br/><span style="color: #6b7280; font-size: 11px; font-family: monospace;">${e.ref}</span>
        </td>
        <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; color: #374151;">
          ${e.desc}
        </td>
        <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; text-align: right; font-weight: 600; color: ${isBill ? '#b91c1c' : '#9ca3af'};">
          ${isBill ? `+₹${e.debit.toLocaleString('en-IN')}` : '-'}
        </td>
        <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; text-align: right; font-weight: 600; color: ${!isBill ? '#15803d' : '#9ca3af'};">
          ${!isBill ? `-₹${e.credit.toLocaleString('en-IN')}` : '-'}
        </td>
        <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; text-align: right; font-weight: 700; color: #111827;">
          ₹${runningBalance.toLocaleString('en-IN')}
        </td>
      </tr>
    `;
    })
    .join('');

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${customer.name} - Statement</title>
  <style>
    @page { size: A4 portrait; margin: 15mm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #111827;
      background: #ffffff;
      margin: 0;
      padding: 24px;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #111827;
      padding-bottom: 16px;
      margin-bottom: 20px;
    }
    .title { font-size: 22px; font-weight: 800; color: #111827; margin: 0 0 4px 0; }
    .subtitle { font-size: 13px; color: #6b7280; margin: 0; }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      margin: 16px 0 24px 0;
    }
    .card {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 12px 14px;
      background: #f9fafb;
    }
    .card-label { font-size: 11px; text-transform: uppercase; color: #6b7280; font-weight: 600; margin-bottom: 4px; }
    .card-val { font-size: 20px; font-weight: 800; color: #111827; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th {
      background: #f3f4f6;
      padding: 10px 12px;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      font-weight: 700;
      color: #4b5563;
      border-bottom: 2px solid #e5e7eb;
    }
    .btn-bar {
      position: fixed;
      top: 12px;
      right: 12px;
      display: flex;
      gap: 8px;
      background: #ffffff;
      padding: 8px;
      border-radius: 8px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    }
    .btn {
      background: #111827;
      color: #ffffff;
      border: none;
      padding: 8px 16px;
      border-radius: 6px;
      font-size: 13px;
      font-weight: 600;
      cursor: pointer;
    }
    @media print {
      .btn-bar { display: none !important; }
      body { padding: 0; }
    }
  </style>
</head>
<body>
  <div class="btn-bar">
    <button class="btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
  </div>

  <div class="header">
    <div>
      <h1 class="title">${shopName}</h1>
      <p class="subtitle">${shop?.owner_name ? `Prop: ${shop.owner_name} • ` : ''}${shop?.phone || ''}</p>
      ${shop?.address ? `<p class="subtitle" style="font-size: 12px; margin-top: 2px;">${shop.address}</p>` : ''}
      ${shop?.gstin ? `<p class="subtitle" style="font-size: 11px; margin-top: 2px;">GSTIN: ${shop.gstin}</p>` : ''}
    </div>
    <div style="text-align: right;">
      <div style="font-size: 15px; font-weight: 800; color: #111827; letter-spacing: 1px;">CUSTOMER STATEMENT</div>
      <div style="font-size: 12px; color: #6b7280; margin-top: 4px;">Date: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
    </div>
  </div>

  <div style="display: flex; justify-content: space-between; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px;">
    <div>
      <div style="font-size: 11px; text-transform: uppercase; color: #6b7280; font-weight: 600;">Bill To Customer</div>
      <div style="font-size: 16px; font-weight: 800; color: #111827; margin-top: 2px;">${customer.name}</div>
      <div style="font-size: 13px; color: #4b5563; margin-top: 2px;">📱 ${customer.phone}</div>
      ${customer.address_landmark ? `<div style="font-size: 12px; color: #6b7280; margin-top: 2px;">📍 ${customer.address_landmark}</div>` : ''}
    </div>
    <div style="text-align: right;">
      <div style="font-size: 11px; text-transform: uppercase; color: #6b7280; font-weight: 600;">Total Outstanding</div>
      <div style="font-size: 22px; font-weight: 900; color: #dc2626; margin-top: 2px;">₹${balanceDue.toLocaleString('en-IN')}</div>
    </div>
  </div>

  <div class="summary-grid">
    <div class="card">
      <div class="card-label">Total Credit Issued</div>
      <div class="card-val" style="color: #b91c1c;">₹${totalCredit.toLocaleString('en-IN')}</div>
    </div>
    <div class="card">
      <div class="card-label">Total Payments Received</div>
      <div class="card-val" style="color: #15803d;">₹${totalPaid.toLocaleString('en-IN')}</div>
    </div>
    <div class="card" style="background: #fef2f2; border-color: #fecaca;">
      <div class="card-label" style="color: #991b1b;">Net Balance Due</div>
      <div class="card-val" style="color: #dc2626;">₹${balanceDue.toLocaleString('en-IN')}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="text-align: left;">Date</th>
        <th style="text-align: left;">Type / Ref</th>
        <th style="text-align: left;">Particulars</th>
        <th style="text-align: right;">Debit (+)</th>
        <th style="text-align: right;">Credit (-)</th>
        <th style="text-align: right;">Balance</th>
      </tr>
    </thead>
    <tbody>
      ${rowsHtml || '<tr><td colspan="6" style="text-align:center; padding: 24px; color: #9ca3af;">No transaction records found.</td></tr>'}
    </tbody>
  </table>

  <div style="margin-top: 36px; display: flex; justify-content: space-between; align-items: flex-end; border-top: 1px solid #e5e7eb; padding-top: 16px;">
    <div style="font-size: 11px; color: #6b7280; max-width: 320px;">
      * This is a computer-generated ledger statement issued by ${shopName}. All transactions are recorded sequentially.
    </div>
    <div style="text-align: center; width: 180px;">
      <div style="border-bottom: 1px solid #9ca3af; height: 32px; margin-bottom: 4px;"></div>
      <div style="font-size: 11px; font-weight: 600; color: #4b5563;">Authorized Signature</div>
    </div>
  </div>
</body>
</html>
  `;

  const printWindow = window.open('', '_blank', 'width=850,height=900');
  if (printWindow) {
    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();
  }
}
